version: "3"

services:
  bancamarchatm:
    image: developodo/bancamarchatm:v1
    container_name: bancamarchatm
    env_file: 
      - "./data/.env"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/ssl:/etc/nginx/ssl/
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    command: /bin/sh -c "envsubst < /usr/share/nginx/html/assets/env.pre.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"
#openssl genrsa -aes256 -passout pass:1234 -out server.pass.key 4096
#openssl rsa -passin pass:1234 -in server.pass.key -out server.key
#rm server.pass.key
#openssl req -new -key server.key -out server.csr
#openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt
#rm server.csr

#docker-compose up


